import './svg/check.svg.js'
import './svg/cross.svg.js'
import './svg/date.svg.js'
import './svg/down.svg.js'
import './svg/error.svg.js'
import './svg/info.svg.js'
import './svg/loading.svg.js'
import './svg/left.svg.js'
import './svg/right.svg.js'
import './svg/star.svg.js'
import './svg/success.svg.js'
import './svg/up.svg.js'

export { registerSvgIcon, parseSvg, getRegisteredSvgIcon } from './store.js'
