export const __font_family: string
export const __transition_duration: string
export const __bg_base: string
export const __bg_base_header: string
export const __dark_bg_base: string
export const __dark_bg_base_header: string
export const __bg_base_hover: string
export const __dark_bg_base_hover: string
export const __bg_base_active: string
export const __dark_bg_base_active: string
export const __fg_base: string
export const __dark_fg_base: string
export const __fg_base_hover: string
export const __dark_fg_base_hover: string
export const __fg_base_active: string
export const __dark_fg_base_active: string
export const __fg_secondary: string
export const __fg_placeholder: string
export const __bg_disabled: string
export const __fg_disabled: string
export const __height_base: string
export const __height_small: string
export const __height_large: string
export const __font_size_base: string
export const __font_size_small: string
export const __font_size_large: string
export const __radius_base: string
export const __radius_small: string
export const __radius_large: string
export const __color_primary: string
export const __color_primary_light: string
export const __color_primary_dark: string
export const __color_danger: string
export const __color_danger_light: string
export const __color_danger_dark: string
export const __color_warning: string
export const __color_warning_light: string
export const __color_warning_dark: string
export const __color_success: string
export const __color_success_light: string
export const __color_success_dark: string
export const __border_color_base: string
export const __dark_border_color_base: string
export const __border_color_light: string
export const __dark_border_color_light: string
export const __border_color_disabled: string
export const __dark_border_color_disabled: string
export const __z_index_popup_base: string
export const __z_index_popup_focus: string
export const __z_index_dialog_base: string
export const __z_index_dialog_focus: string
export const __z_index_drawer_base: string
export const __z_index_drawer_focus: string
export const __padding_base: string
export const __padding_small: string
export const __padding_large: string
