export const ENV_PREFIX = 'env'
export const ELEMENT_PREFIX = 'e'
export const TEXT_PREFIX = 't'
export const ATTR_PREFIX = 'a'
export const IF_PREFIX = 'if'
export const FOR_PREFIX = 'for'
export const HTML_PREFIX = 'html'
